//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soru_cevap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerID { get; set; }
        public string Body { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Users Users { get; set; }
    }
}
